version: '3'

services:
  web:
    container_name: starkbank-teste-demo
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development


